CREATE TABLE TEMPORAL(
    TEMP_YEAR VARCHAR(4),
    TEMP_WATER_HEIGHT VARCHAR(25),
    TEMP_TOTAL_DEATHS VARCHAR(25),
    TEMP_TOTAL_DAMAGE VARCHAR(25),
    TEMP_TOTAL_HOUSES_DESTROYED VARCHAR(25),
    TEMP_TOTAL_HOUSES_DAMAGED VARCHAR(25),
    TEMP_COUNTRY VARCHAR(100)
);

CREATE TABLE TB_YEAR(
    ID_Fecha int IDENTITY(1,1) PRIMARY KEY,
    Fecha int
);

CREATE TABLE TB_COUNTRY(
    ID_Pais int IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100)
);

CREATE TABLE TSUNAMI(
    ID_Tsunami int IDENTITY(1,1) PRIMARY KEY,
    ID_Fecha INT REFERENCES TB_YEAR(ID_Fecha),
    ID_Pais INT REFERENCES TB_COUNTRY(ID_Pais),
    Water_height FLOAT,
    Total_deaths INT,
    Total_damage FLOAT,
    Total_houses_destroyed INT,
    Total_houses_damaged INT
);